DEFAULT_INTERNAL_POWER_ENTRIES = [
    {'entry_name': '攻击', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '力量/气海', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '赛年伤害/治疗提高', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '最小攻击', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '最大攻击', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '流派克制', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '破防', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '会心', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '耐力', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '根骨', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '身法', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '内功防御', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '首领抵御', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '流派抵御', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '抗会心', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '防御', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '气血上限', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '首领克制', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '抗内功会心', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '抗外功会心', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '外功防御', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
    {'entry_name': '灵韵', 'conversion_percent': None, 'conversion_desc': '', 'status': '0', 'remark': '内置内功词条'},
]
