CREATE TABLE IF NOT EXISTS guild_battle_invite (
  invite_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '邀请ID',
  invite_code VARCHAR(64) NOT NULL COMMENT '邀请码',
  owner_user_id BIGINT NOT NULL DEFAULT 0 COMMENT '帮会大当家用户ID',
  guild_name VARCHAR(64) DEFAULT '' COMMENT '帮会名称快照',
  battle_name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '约战名称',
  battle_time DATETIME NULL COMMENT '约战时间',
  expire_time DATETIME NOT NULL COMMENT '链接过期时间',
  status CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态（0启用 1停用）',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
  remark VARCHAR(500) DEFAULT '' COMMENT '备注',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0正常 1删除）',
  PRIMARY KEY (invite_id),
  UNIQUE KEY uk_guild_battle_invite_code (invite_code),
  KEY idx_guild_battle_invite_owner (owner_user_id),
  KEY idx_guild_battle_invite_expire (expire_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='约战临时邀请链接表';

CREATE TABLE IF NOT EXISTS guild_battle_registration (
  registration_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '报名ID',
  invite_id BIGINT NULL COMMENT '邀请ID',
  invite_code VARCHAR(64) DEFAULT '' COMMENT '邀请码快照',
  battle_id BIGINT NULL COMMENT '约战ID',
  guild_id BIGINT NOT NULL DEFAULT 0 COMMENT '帮会ID',
  owner_user_id BIGINT NOT NULL DEFAULT 0 COMMENT '帮会大当家用户ID',
  applicant_user_id BIGINT NOT NULL DEFAULT 0 COMMENT '报名账号用户ID，公开报名为0',
  member_id BIGINT NULL COMMENT '成员ID',
  team_id BIGINT NULL COMMENT '团队ID',
  registration_type VARCHAR(20) DEFAULT 'signup' COMMENT '申请类型(signup/leave)',
  player_name VARCHAR(30) NOT NULL DEFAULT '' COMMENT '玩家名快照',
  player_class VARCHAR(20) DEFAULT '' COMMENT '主职业',
  secondary_class VARCHAR(20) DEFAULT '' COMMENT '副职',
  role_in_guild VARCHAR(20) DEFAULT '' COMMENT '帮会身份',
  applicant_name VARCHAR(50) DEFAULT '' COMMENT '报名人称呼',
  applicant_contact VARCHAR(100) DEFAULT '' COMMENT '联系方式',
  apply_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '报名时间',
  approval_status CHAR(1) DEFAULT '0' COMMENT '审核状态（0待审核 1已通过 2已拒绝）',
  approval_time DATETIME NULL COMMENT '审核时间',
  approval_by VARCHAR(64) NULL COMMENT '审核人',
  approval_comment VARCHAR(500) NULL COMMENT '审核备注',
  remark VARCHAR(500) DEFAULT '' COMMENT '备注',
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0正常 1删除）',
  PRIMARY KEY (registration_id),
  KEY idx_guild_battle_registration_invite (invite_id),
  KEY idx_guild_battle_registration_owner_status (owner_user_id, approval_status),
  KEY idx_guild_battle_registration_member (member_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='约战报名表';
