ARG BASE_IMAGE=nginx:1.27-alpine
FROM ${BASE_IMAGE}

ARG BUILD_REVISION=unknown
ARG BUILD_DATE=unknown
LABEL org.opencontainers.image.revision=$BUILD_REVISION \
      org.opencontainers.image.created=$BUILD_DATE \
      org.opencontainers.image.source="https://github.com/Jiajiazi886/nsh"

RUN rm -rf /usr/share/nginx/html/*
COPY dist /usr/share/nginx/html
COPY bin/nginx.dockermy.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
